//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefreshDataWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimProductItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimProductItem()
        {
            this.FactSale = new HashSet<FactSale>();
        }
    
        public long ProductKey { get; set; }
        public long ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public string ProducerName { get; set; }
        public string CategoryName { get; set; }
        public decimal RetailUnitPrice { get; set; }
        public decimal WeightPerUnit { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactSale> FactSale { get; set; }
    }
}
