//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefreshDataWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactSale
    {
        public long SaleKey { get; set; }
        public long CustomerKey { get; set; }
        public long SupplierKey { get; set; }
        public long ProductKey { get; set; }
        public string InvoiceNum { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Amount { get; set; }
        public decimal TaxRate { get; set; }
        public decimal TaxAmount { get; set; }
        public long InvoiceID { get; set; }
    
        public virtual DimCustomer DimCustomer { get; set; }
        public virtual DimProductItem DimProductItem { get; set; }
        public virtual DimSupplier DimSupplier { get; set; }
        public virtual DimDate DimDate { get; set; }
    }
}
