//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefreshDataWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadedDataInfo
    {
        public int DataKey { get; set; }
        public string TableName { get; set; }
        public System.DateTime LoadStart { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool Successful { get; set; }
        public string ErrorMessage { get; set; }
    }
}
